version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    environment:
      POSTGRES_DB: online_electronics_store_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vasya_3010
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: electronics-backend
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/online_electronics_store_v2
      - DB_USERNAME=postgres
      - DB_PASSWORD=Vasya_3010
    depends_on:
      - postgres

volumes:
  pg_data: