spring.application.name=OnlineElectronicsStore

# ==========================
# DATABASE CONFIGURATION
# ==========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Vasya_3010}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true

# ==========================
# LOGGING
# ==========================
logging.level.org.springframework.security=DEBUG
logging.level.root=ERROR
logging.level.org.springframework=DEBUG

# ==========================
# FILE UPLOAD
# ==========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
